# Generated by Django 2.2.2 on 2021-09-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenralInquery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
