# Generated by Django 2.2.2 on 2021-09-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.CharField(choices=[('1', 'Very bad'), ('2', 'Bad'), ('3', 'Good'), ('4', 'Very good'), ('5', 'Excellent')], max_length=255),
        ),
    ]
