# Generated by Django 2.2.2 on 2021-09-19 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_aboutusdetail_contactdetail_sliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('gallary', models.FileField(upload_to='trip_photos')),
                ('Itinerary', models.TextField()),
                ('region', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('starting_date', models.DateTimeField(blank=True, null=True)),
                ('ending_date', models.DateTimeField(blank=True, null=True)),
                ('Availability', models.BooleanField(blank=True, default=False, null=True)),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('all_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.AllCategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Category')),
                ('inclusion', models.ManyToManyField(related_name='package_inclusion', to='travel.Inclusion')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.SubCategory')),
            ],
        ),
    ]
