# Generated by Django 2.2.2 on 2021-09-19 09:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='Itinerary',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='packages',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
