# Generated by Django 2.2.2 on 2021-09-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_auto_20210919_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagesGallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='packages/images')),
                ('packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.Packages')),
            ],
        ),
    ]
