# Generated by Django 2.2.2 on 2021-09-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_packagesgallary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='gallary',
            new_name='image',
        ),
    ]
