# Generated by Django 2.2.2 on 2021-09-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_auto_20210919_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='rating',
            field=models.CharField(choices=[('1', 'ONE'), ('2', 'TWO'), ('3', 'THREE'), ('4', 'FOUR'), ('5', 'FIVE')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='views',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
