# Generated by Django 2.2.2 on 2021-09-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_auto_20210920_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
