# Generated by Django 2.2.2 on 2021-09-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210923_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(default='123456789'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
